### PR TITLE
Add support for router base options

### PR DESCRIPTION
**Pull request by BrockReece**
Hey,

Thanks for the awesome package, I really enjoyed reading the Medium article on how it all works too.

Anyway, enough fanboyin', I noticed that this doesn't take into account the base url option of the router instance, I have added a snippet that should handle it.

Let me know if there is anything else I can do
Brock

### CODE REVIEW

**Comment by callumacrae** [comment]
Hey, thanks for your pull request!

Have you tested this change? I don't think it will work - you're reassigning a constant. You can use [npm link](https://docs.npmjs.com/cli/link) to install a local version of a package to test it :)

**Comment by BrockReece** [comment]
You are right, sorry about that.
I did test locally, but didn't commit my whole change because it had some console debugging in.
I will test again tonight.

**Comment by callumacrae** [comment]
great, thanks! let me know if you need any help testing :)

**Comment by BrockReece** [comment]
Hey, sorry for the delay.
I have fixed that issue now and it is working for me locally after building and linking to my project.

Let me know if there is anything else I can do to help.

**Comment by callumacrae** [comment]
@BrockReece sorry, i missed your reply! is this still something you need?

**Comment by markcarver** [comment]
This is sorely needed...

**Comment by callumacrae** [comment]
@markcarver happy to merge and release but don't have any project I can test it in at the moment - would you be able to give it a test and let me know if it works?

**Comment by markcarver** [comment]
It works


Typos courteous of Siri

**Comment by callumacrae** [comment]
Merged and published as 1.1.0 :)

**Pull request merged**
